import Head from 'next/head'
import Coluna1 from './colunas/coluna1'
import Coluna2 from './colunas/coluna2'
import Coluna3 from './colunas/coluna3'
import Coluna4 from './colunas/coluna4'
import Coluna5 from './colunas/coluna5'
import colunas from '../../styles/colunas.module.css'

export default  function Dashboard() {

  return (
    <>

    <Head>
    <title>OPPLOG</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  
    <div className={colunas.bottomdiv}>
          <div className={colunas.colunaDiv}>
              <div className={colunas.containerColunas}><Coluna1 /></div>
          </div>
          <div className={colunas.colunaDiv}>
              <div className={colunas.containerColunas}><Coluna2 /></div>
          </div>
          <div className={colunas.colunaDiv}>
              <div className={colunas.containerColunas}><Coluna3 /></div>
          </div>
          <div className={colunas.colunaDiv}>
              <div className={colunas.containerColunas}><Coluna4 /></div>
          </div>
          <div className={colunas.colunaDiv}>
              <div className={colunas.containerColunas}><Coluna5 /></div>
          </div>
          
  
    

    </div>

    </>
    

  )
}