import Head from 'next/head'


export default  function Menu() {

  return (
    <>

    <Head>
    <title>OPPLOG</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

    <body>
    <div className='menuBar'>
    <p>
      
        </p>

    </div>

    </body>

    </>
    

  )
}

