import Head from 'next/head'
import Dashboard from '../components/dashboard'
import Menu from '../components/menu'


export default  function Plataforma() {

  return (
    <>

    <Head>
    <title>OPPLOG</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

    <main>

    <header>

    Se existe ? logotipo E nome do usuario : apagar

    </header>

    <aside className='menuBar'>

    <Menu />

    </aside>

    <content className='mainPage'>
    <Dashboard />

    </content>

   
    </main>

    </>
    

  )
}

