import Head from 'next/head'
import Dashboard from '../components/dashboard'
import Menu from './menu'
import dashstyle from "../../styles/colunas.module.css"
import QuickAdd from ".././components/cards/quickAdd"
import { useState } from "react"



export default  function Plataforma() {
  const [addCard, setAddCard] = useState(false)

  return (
    <>

    <Head>
    <title>OPPLOG</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <main className={dashstyle.maindiv}>

  <header className={dashstyle.header}>
    <a href='http://localhost:3000/'><img className={dashstyle.logoPossi}src="Logo-dashboard.svg"></img></a>
      

     </header>

    <aside className='menuBar'>

    <Menu />
   

    </aside>

    <content className='mainPage'>
    <Dashboard />

    </content>

    </main>

    </>
    

  )
}

