import Head from 'next/head'

export default  function Entrevista() {
  return (
    <Head>
    <title>APPLOG</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  )
}

