import Head from 'next/head'
import Dashboard from './components/dashboard'
import Menu from './menu'
// import styles from '../styles/Home.module.css'

export default function HomePage() {
  return (
    <div>

      <Head>
        <title>APPLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className='menuBar'>
          <a href="#">
            <Menu />
          </a>

        </div>
{/*

    ****DÚVIDA"""""

    Se a página actual for alguma coisa de ... filtro? 
    O gajo mostra o dashfilter, caso contrário mostra o dashboard

*/}
        <div className='mainDashboard'>
            <Dashboard />

        </div>

    </div>


  )
}

