import Head from 'next/head'

export default function Landing() {
  return (
    <div>
      <Head>
        <title>OPPLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <content>
          <h1>LOGO</h1>
          <p>Welcome to your new Job!</p>

          {/* BOTOES!!!! */}
          <button label="Sign Up" >Sign Up</button>

          <button label="Log In">Login</button>

          {/* <button onClick={VAIS PARA A COMPONENT/FORMULARIO DO LOGIN}>Login</button>
      
      <button onClick={VAIS PARA A COMPONENT/FORMULARIO DO REGISTO}>Sign up</button> */}

        </content>

        <aside>

        </aside>
        <footer>Botões
          <a href="https://facebook.com" /> facebook github insta about us </footer>
      </main>


    </div>
  )
}

