import Head from 'next/head'
import { useState } from "react"

export default function Login() {
  const [loginData, setloginData] = useState({
    EmailAddress: "aaa@aaa.aa",
    Password: "password"
  })
  const login = async () => {
    const res = await fetch(
      '../../api/login', {
      body: JSON.stringify(loginData),
      headers: {
        "Content-Type": "application/json",
      },
      method: "POST"
    })
    const json = await res.json()
    console.log(loginData, res.status, json)
    localStorage.setItem("token", json.token)
  }

  return (
    <>
      <Head>
        <title>OPPLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <aside>
          <h1>LOGO</h1>
          <p>Welcome to your new Job!</p>
        </aside>

        <form onSubmit={(e) => { e.preventDefault(), login() }}>

          <label> Email
            <input
              type="email"
              onChange={(e) => setloginData({ ...loginData, EmailAddress: e.target.value })}
              name="description"
              placeholder="Email"
              autoComplete="off"
              required />
          </label>

          <label> Password
            <input
              type="password"
              name="description"
              onChange={(e) => setloginData({ ...loginData, Password: e.target.value })}
              placeholder="Inserir Password"
              autoComplete="off"
              required /></label>

          <button
            value="Sign Up">
            Login
          </button>
            <h3>{JSON.stringify(loginData)}</h3>
        </form>

        <footer>copyright</footer>
      </main>
    </>
  )
}

