import Head from 'next/head'
import { useState } from "react"
import { validateEmail } from './functions_auth'
// import {Formik, Form} from 'formik'
// import {TextField} from './TextField'
import { testEmail } from '../../../services/auth'

export default function Signup() {
  const [signupData, setSignupData] = useState({
    Name: 'name',
    Phone_Number: 'tel',
    Email_Address: 'email',
    Password: 'password',
  })

  return (
    <>

      <Head>
        <title>OPPLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>


        <aside>

          <h1>LOGOTIPO</h1>
          <p>Regista-te</p>
          {/* <img>VAI TER AQUI UMA IMAGEM</img> */}

        </aside>


        <form onSubmit={(e) => {
          e.preventDefault()
        }}>

          <label>Nome</label>
          <input type="text" autoComplete="off"></input><br />
          <label>Apelido</label>
          <input type="text" autoComplete="off"></input><br />

          <label>Contacto Móvel</label>
          <input type="tel"></input><br />

          <label>Email</label>
          <input type="email" name="description" onChange={(e) => setSignupData({ ...signupData, Email_Address: e.target.value })} placeholder="Email" autoComplete="off" />
          <p>{!validateEmail(signupData.Email_Address) && "Please insert a valid email address."}</p>

          <label>Password</label>
          <input type="password" name="description" placeholder="Inserir Password" autoComplete="off" /><br />

          <label>Confirmar Password</label>
          <input type="password" name="description" placeholder=""></input><br />

          <label>Aceitar Termos e Condições</label>
          <input type="checkbox" name=""></input><br />

          <input type="submit" value="Registar"></input>



        </form>



        <footer>copyright</footer>
      </main>
    </>
  )
}

